---
- name: Check if Bloodhound is already installed
  ansible.builtin.stat:
    path: "{{ ludus_bloodhound_ce_install_path }}/docker-compose.yml"
  register: bh_installed

- name: Show message
  ansible.builtin.debug:
    msg: "Bloodhound is already installed - to run this play again remove the directory {{ ludus_bloodhound_ce_install_path }}"
  when: bh_installed.stat.exists

- name: Make bloodhound directory
  become: true
  ansible.builtin.file:
    path: "{{ ludus_bloodhound_ce_install_path }}"
    state: directory
    mode: "0755"
  when: not bh_installed.stat.exists

- name: Copy the docker-compose.yml file
  become: true
  ansible.builtin.copy:
    src: docker-compose.yml
    dest: "{{ ludus_bloodhound_ce_install_path }}/docker-compose.yml"
    mode: "0644"
  when: not bh_installed.stat.exists

- name: Copy the .env template to the host
  ansible.builtin.template:
    src: env.j2
    dest: "{{ ludus_bloodhound_ce_install_path }}/.env"
    mode: "0600"
  when: not bh_installed.stat.exists

- name: Write the password to a file on the remote host
  ansible.builtin.lineinfile:
    path: "{{ ludus_bloodhound_ce_install_path }}/bloodhound_admin_password.txt"
    line: "{{ ludus_bloodhound_admin_password }}"
    mode: "0600"
    create: true
  when: not bh_installed.stat.exists

- name: If ludus_bloodhound_listen_only_localhost is false, Add to .env file
  ansible.builtin.lineinfile:
    path: "{{ ludus_bloodhound_ce_install_path }}/.env"
    line: "BLOODHOUND_HOST='0.0.0.0'"
    mode: "0644"
  when: not bh_installed.stat.exists and not ludus_bloodhound_listen_only_localhost

- name: Start BH-CE Docker Containers
  become: true
  ansible.builtin.shell:
    cmd: |
      cd {{ ludus_bloodhound_ce_install_path }}
      docker compose up -d
  when: not bh_installed.stat.exists

- name: BH-CE Installation Complete
  ansible.builtin.debug:
    msg: "Bloodhound is up and running!"
  when: not bh_installed.stat.exists

- name: BH-CE Credz
  ansible.builtin.debug:
    msg: "Access BH-CE at http://{{ ansible_host }}:{{ ludus_bloodhound_port }} using admin -> {{ ludus_bloodhound_admin_password }}"
  when: not bh_installed.stat.exists
